import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../../styles/Home.module.css";
import { getApiClient } from "../rest/client";

type Props = {
  name: string;
};

const Home: NextPage<Props> = ({ name }) => {
  const [value, setName] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{name}</h1>
        <form
          onSubmit={async (e) => {
            e.preventDefault();
            await getApiClient().postUser({ name: value });
            setName("");
          }}
        >
          <label htmlFor="name">name:</label>
          <input
            id="name"
            type="text"
            value={value}
            onChange={(e) => setName(e.target.value)}
          />
          <button>Add User</button>
        </form>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const data = await getApiClient().getUser({ params: { id: 1 } });
  return { props: { name: data.name } };
};

export default Home;
